import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useQuery } from "react-query";
import { useEffect, useState } from "react";

// export async function getStaticProps() {
//   const category = await fetch("http://127.0.0.1:9999/api/category");
//   const categoryData = await category.json();
//   const subCategory = await fetch("http://127.0.0.1:9999/api/sub_category");
//   const subCategoryData = await subCategory.json();

//   return {
//     props: {
//       categoryData,
//       subCategoryData,
//     },
//   };
// }

// export async function getStaticProps() {
//   const res = await fetch("http://10.7.3.4:9000/user/posts");
//   const data = await res.json();

//   return {
//     props: {
//       data,
//     },
//   };
// }

export default function Home() {
  const { data: categoryData } = useQuery("category", async () => {
    const res = await fetch("http://10.7.3.4:9000/user/posts");
    const data = await res.json();
    return data;
  });

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 더미 데이터 */}
      <div className={styles.container}>
        {categoryData?.map((category: any) => (
          <div key={category._id}>
            <h1>{category.name}</h1>
          </div>
        ))}
      </div>
    </>
  );
}
