import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useQuery } from "react-query";

export async function getStaticProps() {
  const res = await fetch("http://localhost:9000/user/posts");
  const data = await res.json();

  return {
    props: {
      data,
    },
  };
}

export default function Home({ data }: any) {
  // const { data, isLoading, isError } = useQuery("posts", () =>
  //   fetch("http://localhost:9000/user/posts").then((res) => res.json())
  // );

  // if (isLoading) return <div>Loading...</div>;

  // if (isError) return <div>Error...</div>;

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* 더미 데이터 */}
      <div className={styles.container}>
        {data?.map((post: any) => (
          <div key={post.id}>
            <h1>{post.title}</h1>
            <p>{post.description}</p>
          </div>
        ))}
      </div>
    </>
  );
}
